### ISSUE TITLE
language server has something wrong, restart repeat

### ISSUE THREAD

**Issue by chenyidao110** [microsoft/pyright#1092]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
While edit python file whith language-server pyright, it notes language server starting exited with status exit, do you want to restart it?(y/n), after enter y ,issue repeat again
![pyright](https://user-images.githubusercontent.com/14362421/95292837-dec45680-08a4-11eb-8ec7-53f4be1f880b.png)

**Additional context**
pyright:error info as follow:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.5013 (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-langserver.js:1:561)
    at s (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-langserver.js:1:687)
    at Object.8863 (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-internal.js:1:786936)
    at s (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-langserver.js:1:687)
    at Object.5822 (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-langserver.js:1:46)
    at s (/home/test/.emacs.d/.cache/lsp/npm/pyright/lib/node_modules/pyright/dist/pyright-langserver.js:1:687)

Process pyright stderr finished
internal/modules/cjs/loader.js:638
    throw err;

**Comment by erictraut** [comment]
Are you running the language server in VS Code or some other environment? It looks like you're trying to run it in an old version of node that doesn't support worker threads.

**Comment by chenyidao110** [comment]
> Are you running the language server in VS Code or some other environment? It looks like you're trying to run it in an old version of node that doesn't support worker threads.

I use emacs;as you said , should I upgrade nodejs?

**Comment by erictraut** [comment]
Yes, the package.json for the language server indicates that it requires node 12.0.0 or newer.

**Comment by chenyidao110** [comment]
> 
> 
> Yes, the package.json for the language server indicates that it requires node 12.0.0 or newer.

After upgrade node to v12.19.0, language server work normally. Thank you!
