### ISSUE TITLE
Pyright server crashed in pyright 1.0.45

### ISSUE THREAD

**Issue by tomopy03** [microsoft/pyright#170]
**Describe the bug**
Pyright server crashed in pyright `1.0.45`.
Pop up message of "The Pyright server crashed 5 times in the last 3 minutes. The server will not be restarted."

**To Reproduce**

1. Update pyright `1.0.42` to `1.0.45`.
2. Restart VSCode.
3. Pyright server crashed.

**Expected behavior**

**Screenshots or Code**
```
/home/tomopy03/.vscode-server/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24
                throw new Error('Client doesn\'t support sending workspace folder change events.');
                ^

Error: Client doesn't support sending workspace folder change events.
    at Object.get onDidChangeWorkspaceFolders [as onDidChangeWorkspaceFolders] (/home/tomopy03/.vscode-server/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24:23)
    at Object.<anonymous> (/home/tomopy03/.vscode-server/extensions/ms-pyright.pyright-1.0.45/server/server.js:267:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
Pyright language server starting
[Info  - 17:15:11] Connection to server got closed. Server will restart.
/home/tomopy03/.vscode-server/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24
                throw new Error('Client doesn\'t support sending workspace folder change events.');
                ^
```

**VS Code extension or command-line**
I'm running the pyright VS Code extension version `1.0.45`.
But, `1.0.44` not crash.

**Additional context**

**Comment by nicocti** [comment]
Same here, with VSCode version:

```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic
```

**Comment by dennisli92** [comment]
Glad I stumbled on this, was going insane trying to figure this out on my machine too :) 

Also running 1.0.45
```
/Users/user/.vscode/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24
                throw new Error('Client doesn\'t support sending workspace folder change events.');
                ^

Error: Client doesn't support sending workspace folder change events.
    at Object.get onDidChangeWorkspaceFolders [as onDidChangeWorkspaceFolders] (/Users/user/.vscode/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24:23)
    at Object.<anonymous> (/Users/user/.vscode/extensions/ms-pyright.pyright-1.0.45/server/server.js:267:23)
    at Object.<anonymous> (/Users/user/.vscode/extensions/ms-pyright.pyright-1.0.45/server/server.js:334:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
[Info  - 5:39:45 AM] Connection to server got closed. Server will restart.
Pyright language server starting
/Users/user/.vscode/extensions/ms-pyright.pyright-1.0.45/server/node_modules/vscode-languageserver/lib/workspaceFolders.js:24
                throw new Error('Client doesn\'t support sending workspace folder change events.');
```

**Comment by erictraut** [comment]
Sorry for the regression. I merged hiboshi's fix, and will release a new version shortly.

**Comment by nicocti** [comment]
Thanks @higoshi for the bug fix and @erictraut for the quick release ;)
