### ISSUE TITLE
 language server has something wrong, restart repeat

### ISSUE THREAD

**Issue by lialzmChina** [microsoft/pyright#1978]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

I use nvm install node 14.13.0

**Comment by erictraut** [comment]
You will see this error if you have installed a version of node that is too old. I don't think you're running 14.13.0. Please confirm by running `node --version` from the shell.

**Comment by lialzmChina** [comment]
you are right,I didn’t know the difference between emacs environment variables and system environment variables ,sorry
