### ISSUE TITLE
VS Code Pylance Issue

### ISSUE THREAD

**Issue by OsamaRF19** [microsoft/pyright#2086]
I am a new user to VS code and learning python. I was practicing my code when all of sudden Pylance stopped showing me the variable colors, the function suggestion and other features. Considering this a simple issue, i reinstalled Python, Pylance and still nothing changed. Still the problem wasn't fixed so i reinstalled VS code 3 times after downloading it again from Microsoft website and still it's not working Correctly. Searched on google about this issue but couldn't get the solution. 

This is the error it shows when i use 'python' in output of code:

User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
Python interpreter path: /usr/bin/python3
Error 2021-07-15 09:47:55: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/osama/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/osama/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167834)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version

**Comment by erictraut** [comment]
Thanks for the bug report. This isn't a core type checker issue, so I'm going to transfer it to the pylance-release repo so it gets the appropriate attention.
