### ISSUE TITLE
pyright server won't start: Error: Cannot find module 'worker_threads' using WSL2

### ISSUE THREAD

**Issue by saltsucker** [microsoft/pyright#3062]
**Describe the bug**
When running `pyright` on WSL2 I get this error:

```Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.1267 (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-langserver.js:1:494)
    at s (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-langserver.js:1:670)
    at Object.9560 (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-internal.js:1:782328)
    at s (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-langserver.js:1:670)
    at Object.6334 (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-internal.js:1:1052978)
    at s (/mnt/c/Users/user/AppData/Roaming/npm/node_modules/pyright/dist/pyright-langserver.js:1:670)
```

**To Reproduce**
install and enable WSL2 and try to run pyright.

**Expected behavior**
I expect the pyright server to start when opening a python file.

**VS Code extension or command-line**
command-line
Which version? v1.1.222 (checked on windows side)

**Additional context**
I found this error when trying to use lsp server in spacemacs.
```
which pyright
/mnt/c/Users/user/AppData/Roaming/npm/pyright
```

**Comment by erictraut** [comment]
That error is an indication that the version of node that you've installed is really old. Please update your node to the latest version, and it should work fine.

**Comment by saltsucker** [comment]
Ya, that was issue. I thought, given that path in the error, that it was using my windows nodejs (v17), but I guess it was using my ubuntu (v10). I installed nvm and used that to install the newer versions of node and that resolved my issue. Sorry to waste your time :(
