### ISSUE TITLE
Pyright doesn't work on M1

### ISSUE THREAD

**Issue by Mariownyou** [microsoft/pyright#3199]
I've tried to install this with `brew` and `brew` using Rosetta. I also tried to install using `npm` and `pip`  

`pyright` gives this
```
/Users/mariownyou/.nvm/versions/node/v8.14.0/lib/node_modules/pyright/dist/vendor.js:2
exports.id=736,exports.ids=[736],exports.modules={3574:(A,e,t)=>{"use strict";const r=t(9149),o=global.Date;class i extends o{constructor(A){super(A),this.isDate=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}`}}A.exports=A=>{const e=new i(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},8477:(A,e,t)=>{"use strict";const r=t(9149);class o extends Date{constructor(A){super(A+"Z"),this.isFloating=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}T${r(2,this.getUTCHours())}:${r(2,this.getUTCMinutes())}:${r(2,this.getUTCSeconds())}.${r(3,this.getUTCMilliseconds())}`}}A.exports=A=>{const e=new o(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},350:A=>{"use strict";A.exports=A=>{const e=new Date(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},7571:(A,e,t)=>{"use strict"

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.s.f.require (/Users/mariownyou/.nvm/versions/node/v8.14.0/lib/node_modules/pyright/dist/pyright.js:1:1958)
```

**Comment by erictraut** [comment]
An "unexpected token" error sounds like you might have a really old version of node installed. Could you confirm that you are running the latest stable version? You can type `node --version` to see which version you're running.

**Comment by JelleZijlstra** [comment]
The output has `node/v8.14.0`, so I'm guessing they're running node 8? That's indeed quite old.

**Comment by erictraut** [comment]
Ah, good spot. I missed that. Yeah, that would explain the problem. You're using an ancient version of node. If you upgrade to a more modern version, the problem should go away.

**Comment by Mariownyou** [comment]
Yeah, missed that. our project use old one. With latest version everything is fine. thank you
