### ISSUE TITLE
pip-installed pyright hangs

### ISSUE THREAD

**Issue by ikamensh** [microsoft/pyright#3232]
Hello,

I've been previously using npm-installed pyright, and it worked. I was excited to try pip installed version, however it didn't work, not producing any useful input on --version or call w/o arguments.

**Describe the bug**
Pip installed version of pyright doesn't launch, asked to print version it only set ERRNO to 1 in 1 minute+ running time and made no output.

**To Reproduce**
in Python 3.8.8,
`pip install pyright==1.1.231`
`pyright --version` -> no version outputted, ERRNO set.

(also tried on Python 3.9.6)

**Expected behavior**
Expected pip version of pyright to behave same as npm version.

**Screenshots or Code**
```sh
~ $ pip install pyright                                          (base) 08:08:37
...
Installing collected packages: nodeenv, pyright
Successfully installed nodeenv-1.6.0 pyright-1.1.231
~ $ pyright --version                                            (base) 08:08:45
~ [1] $ pyright --version                                        (base) 08:10:01
^CTraceback (most recent call last):
  File "~/opt/anaconda3/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
  File "~/opt/anaconda3/lib/python3.8/site-packages/pyright/cli.py", line 72, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "~/opt/anaconda3/lib/python3.8/site-packages/pyright/cli.py", line 20, in main
    return run(*args, **kwargs).returncode
  File "~/opt/anaconda3/lib/python3.8/site-packages/pyright/cli.py", line 48, in run
    return node.run('npx', *pre_args, f'pyright@{version}', *args, **kwargs)
  File "~/opt/anaconda3/lib/python3.8/site-packages/pyright/node.py", line 112, in run
    return subprocess.run(node_args, env=env, **kwargs)
  File "~/opt/anaconda3/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "~/opt/anaconda3/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "~/opt/anaconda3/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "~/opt/anaconda3/lib/python3.8/subprocess.py", line 1808, in _wait
    (pid, sts) = self._try_wait(0)
  File "~/opt/anaconda3/lib/python3.8/subprocess.py", line 1766, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**VS Code extension or command-line**
CLI

**Additional context**
MacOs 11.6.3

**Comment by erictraut** [comment]
The pip installer for pyright isn't maintained by us. It is created and maintained by a member of the community. Please report any problems in that project's issue tracker: https://github.com/RobertCraigie/pyright-python.
