### ISSUE TITLE
pyright fails to run

### ISSUE THREAD

**Issue by butchhoward** [microsoft/pyright#3537]
**Describe the bug**
pyright fails to run

**To Reproduce**
$ npm install -g pyright
$ pyright --version
/Users/butchhoward/.nvm/versions/node/v8.0.0/lib/node_modules/pyright/dist/vendor.js:2
exports.id=736,exports.ids=[736],exports.modules={1356:(A,e,t)=>{"use strict";const r=t(2548),o=global.Date;class i extends o{constructor(A){super(A),this.isDate=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}`}}A.exports=A=>{const e=new i(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},4044:(A,e,t)=>{"use strict";const r=t(2548);class o extends Date{constructor(A){super(A+"Z"),this.isFloating=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}T${r(2,this.getUTCHours())}:${r(2,this.getUTCMinutes())}:${r(2,this.getUTCSeconds())}.${r(3,this.getUTCMilliseconds())}`}}A.exports=A=>{const e=new o(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},6347:A=>{"use strict";A.exports=A=>{const e=new Date(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},2110:(A,e,t)=>{"use strict

SyntaxError: Unexpected token *
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.s.f.require (/Users/butchhoward/.nvm/versions/node/v8.0.0/lib/node_modules/pyright/dist/pyright.js:1:1992)

**Expected behavior**
successful run 

**Additional context**
MacOS 12.4
$ python --version
Python 3.9.7
$ nvm --version
0.39.0
$ npm --version
5.0.0
$ node --version
v8.0.0

**Comment by erictraut** [comment]
You are running an ancient version of node. Please install a more recent version, and that should clear things up. Pyright requires a minimum of node v12.

**Comment by butchhoward** [comment]
Doh. Did this change recently? We have been using pyright for quite a while with node 8.0.0 without issue

**Comment by erictraut** [comment]
No, this has been a requirement for a long time — at least a year.
