### ISSUE TITLE
install with pip and run fails with permission error

### ISSUE THREAD

**Issue by szabolcsdombi** [microsoft/pyright#3553]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**

I just installed pyright and wanted to try it to see what is it for and what output it generates on my examples folder.

What I did:

- install with pip
- run with python

What happened:

A long stack trace appeared with some permission errors on the top.

My python and OS version:

```
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
OS: Windows 11 (21H2 22000.675)
```

**To Reproduce**

```
D:\Programming\zengl>python -m pip install pyright
Collecting pyright
  Downloading pyright-1.1.252-py3-none-any.whl (15 kB)
Collecting nodeenv>=1.6.0
  Downloading nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Installing collected packages: nodeenv, pyright
Successfully installed nodeenv-1.6.0 pyright-1.1.252

D:\Programming\zengl>python -m pyright
 * Install prebuilt node (18.3.0) ..... done.
You do not have sufficient privilege to perform this operation.
You do not have sufficient privilege to perform this operation.
Error: Failed to create nodejs.exe link
 * Environment already exists: C:\Users\Szabi\AppData\Local\Temp\pyright-python.Szabi\env
Traceback (most recent call last):
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\__main__.py", line 5, in <module>
    entrypoint()
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\cli.py", line 72, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\cli.py", line 20, in main
    return run(*args, **kwargs).returncode
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\cli.py", line 36, in run
    npx = node.version('npx')
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\node.py", line 116, in version
    proc = run(target, '--version', stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\node.py", line 86, in run
    binary = _ensure_available(target)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\node.py", line 34, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\node.py", line 52, in _ensure_node_env
    _install_node_env()
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyright\node.py", line 79, in _install_node_env
    subprocess.run(args, check=True)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Szabi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'nodeenv', 'C:\\Users\\Szabi\\AppData\\Local\\Temp\\pyright-python.Szabi\\env']' returned non-zero exit status 2.
```

**Expected behavior**

- see what pyright outputs

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
def foo(self) -> str:
    return 3
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

**Comment by JelleZijlstra** [comment]
The pip package is provided by a third party: https://github.com/RobertCraigie/pyright-python. You should probably report this issue on that repo.

**Comment by erictraut** [comment]
As @JelleZijlstra said, this project doesn't maintain the pip install mechanism for pyright. Please report the issue to that project. It looks like you're having problems installing the node runtime, which pyright requires. You could try installing that manually through https://nodejs.org/en/. Node 16.x is the latest stable version.
