### ISSUE TITLE
Pyright fails to recognize valid calls when ParamSpec, Concatenate, and factories are used

### ISSUE THREAD

**Issue by lexicalunit** [microsoft/pyright#3559]
**Describe the bug**
Contrived code but in the real version this makes sense as we're working with `pytest` and using the [factories-as-fixtures pattern](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html?highlight=factories#factories-as-fixtures).

See the inline comments on the three calls to `bulk_maker()` for the `pyright` errors:
```python
from typing import Any, Callable, List

# For python 3.8:
from typing_extensions import Concatenate, ParamSpec, TypeAlias

# For python 3.10:
# from typing import Concatenate, ParamSpec, TypeAlias


class Company:
    id: int

    def __init__(self, id: int):
        self.id = id
        print(self)

    def __repr__(self) -> str:
        return f"<company {self.id}>"


Factory: TypeAlias = Callable[..., Company]


def make_company(*args: Any, **kwargs: Any) -> Company:
    return Company(*args, **kwargs)


P = ParamSpec("P")
BulkFactory: TypeAlias = Callable[Concatenate[int, P], List[Company]]


def make_n_companies() -> BulkFactory[P]:
    def factory(n: int, *args: P.args, **kwargs: P.kwargs) -> List[Company]:
        return [make_company(*args, **kwargs) for _ in range(n)]

    return factory


bulk_maker = make_n_companies()

print()
bulk_maker(5, 10)  # Expected 1 positional argument

print()
bulk_maker(5, id=10)  # No parameter named "id"

print()
bulk_maker(5)  # Arguments for ParamSpec "P@make_n_companies" are missing
```

The first two calls to `bulk_maker()` are fine. The last one is incorrect and will fail at runtime:
```shell
± python example.py

<company 10>
<company 10>
<company 10>
<company 10>
<company 10>

<company 10>
<company 10>
<company 10>
<company 10>
<company 10>

Traceback (most recent call last):
  File "foo.py", line 47, in <module>
    bulk_maker(5)  # Arguments for ParamSpec "P@make_n_companies" are missing
  File "foo.py", line 33, in factory
    return [make_company(*args, **kwargs) for _ in range(n)]
  File "foo.py", line 33, in <listcomp>
    return [make_company(*args, **kwargs) for _ in range(n)]
  File "foo.py", line 24, in make_company
    return Company(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'id'
```

**Expected behavior**
There should not be any `pyright` errors for the first two calls to `bulk_maker()`.

**VS Code extension or command-line**
- _Are you running pyright as a VS Code extension or a command-line tool?_ **Both**
- _Which version?_ **pyright 1.1.253** and **pylance v2022.6.10`
- Error is seen when using python 3.8 and 3.10. No difference.

**Comment by erictraut** [comment]
This is an incorrect usage of ParamSpec. The problem is `P` is scoped to the function `make_n_companies`, but `P` appears only in the return type annotation, so there's no way for `P` to be solved in the context of a call to `make_n_companies`.

If your intent is to support any callable whose first parameter is an `int`, then you should parameterize the ParamSpec with `...`, as in:

```python
def make_n_companies() -> BulkFactory[...]:
   ...
```

The `...` is the equivalent of `Any` for a ParamSpec.

**Comment by erictraut** [comment]
Hmm, this looks like a bug in the runtime handling of `Concatenate`. You can work around it by enclosing the `BulkFactory[...]` in quotes or using `from __future__ import annotations`.

If I understand the problem you're trying to solve here, a ParamSpec isn't the right approach in the first place. A callback protocol would be much more appropriate.

```python
class BulkFactory(Protocol):
    def __call__(
        self, count: int, /, id: int, *args: Any, **kwargs: Any
    ) -> List[Company]:
        ...
```

**Comment by erictraut** [comment]
The runtime exception appears to be a bug in the `typing_extensions` library. I've filed [this issue](https://github.com/python/typing_extensions/issues/48) to track this.

**Comment by lexicalunit** [comment]
@erictraut I tried using the `Protocol` approach and that also has one issue that I can not resolve.

### Example Code
```python
from __future__ import annotations

from typing import Any, Callable, Generic, List, Optional, Protocol, TypeVar

from typing_extensions import ParamSpec, TypeAlias


def i_default() -> int:
    return 4


def s_default() -> str:
    return "foo"


class Company:
    id: int

    def __init__(
        self,
        id: Optional[int] = None,
        # ... dozens more optional properties go here
    ):
        self.id = id or i_default()  # each property has its own default
        print(self)

    def __repr__(self) -> str:
        return f"<company {self.id}>"


class User:
    id: int

    def __init__(
        self,
        uuid: Optional[str] = None,
        # ... dozens more optional properties go here
    ):
        self.uuid = uuid or s_default()  # each property has its own default
        print(self)

    def __repr__(self) -> str:
        return f"<user {self.uuid}>"


_FactoryT = TypeVar("_FactoryT")
Factory: TypeAlias = Callable[..., _FactoryT]


def make_company(*args: Any, **kwargs: Any) -> Company:
    return Company(*args, **kwargs)


def make_user(*args: Any, **kwargs: Any) -> User:
    return User(*args, **kwargs)


T = TypeVar("T")
P = ParamSpec("P")


class BulkFactory(Protocol, Generic[T]):
    def __call__(
        self,
        n: int,
        /,
        *args: Any,
        **kwargs: Any,
    ) -> List[T]:
        ...


def make_n(maker: Callable[P, T]) -> BulkFactory[T]:
    def inner(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T]:
        return [maker(*args, **kwargs) for _ in range(n)]

    return inner


# create our bulk factories for user and company:
make_n_users = make_n(make_user)
make_n_companies = make_n(make_company)

# create a bunch of users and companies:
make_n_users(5)  # this should work, giving us all default values
make_n_users(5, uuid="whatever")  # this should work, giving us some
                                  # default values while others are set

make_n_companies(5)
make_n_companies(5, id=5)
```

### Pylance Issue
On the line `    return inner` we get:
```
(function) inner: (n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]
Expression of type "(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]" cannot be assigned to return type "BulkFactory[T@make_n]"
  Type "(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]" cannot be assigned to type "(n: int, /, *args: Any, **kwargs: Any) -> List[T@make_n]"
    Parameter "**kwargs" has no corresponding parameter
```

**Comment by erictraut** [comment]
Yeah, that looks like a bug. Could you please open a new issue in the [pyright issue tracker](https://github.com/microsoft/pyright/issues) so this doesn't get lost? Thanks!

**Comment by lexicalunit** [comment]
Oh it does? I figured I was just doing something wrong 😅 -- I'll open an issue now.
