### ISSUE TITLE
Internal error while parsing nested dict

### ISSUE THREAD

**Issue by cissoid** [microsoft/pyright#3689]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
```
[ERROR][2022-07-13 17:43:09] ...lsp/handlers.lua:455    'An internal error occurred while binding file "/private/tmp/test.py": Error: Debug Failure. createKeyForReference received unexpected index type
    at createKeyForReference (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowTypes.ts:237:13)
    at C.visitAssignment (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/binder.ts:850:50)
    at C.visitNode (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:132:29)
    at C.walk (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:98:37)
    at forEach (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:107:22)
    at Array.forEach (<anonymous>)
    at C.walkMultiple (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:105:15)
    at C.walk (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/parseTreeWalker.ts:100:18)
    at C._walkStatementsAndReportUnreachable (~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/binder.ts:2584:22)
    at ~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/binder.ts:287:22'

```

**To Reproduce**
If I assign a nested dict, first key is a variable, second key is a string literal, then pyright will report this exception.

```python
d = {}
key = "key"
d[key]["key"] = 1  # this line trigger the bug
```

**Expected behavior**
LSP server should handle file content normally.

**Screenshots or Code**
See code above.

**VS Code extension or command-line**
cli version pyright v1.1.259
Neovim 0.7.2

**Additional context**

**Comment by erictraut** [comment]
I just did a "hot fix" release 1.1.260 that addresses this issue. Apologies for the regression.
