### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'category')

### ISSUE THREAD

**Issue by debonte** [microsoft/pyright#5091]
Pulled from telemetry. We're seeing this regularly. 100-200 hits per week.

TypeError: Cannot read properties of undefined (reading 'category')</br>at category <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/types.ts#L2447'>pyright-internal/src/analyzer/types.ts:2447:16</a></br>    at value <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2620'>pyright-internal/src/analyzer/typeUtils.ts:2620:48</a></br>at Array.filter (<anonymous>)</br>at filter <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2619'>pyright-internal/src/analyzer/typeUtils.ts:2619:42</a></br>at filterClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2645'>pyright-internal/src/analyzer/typeUtils.ts:2645:20</a></br>at type <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17218'>pyright-internal/src/analyzer/typeEvaluator.ts:17218:37</a></br>at classType <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16291'>pyright-internal/src/analyzer/typeEvaluator.ts:16291:74</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17206'>pyright-internal/src/analyzer/typeEvaluator.ts:17206:21</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17204'>pyright-internal/src/analyzer/typeEvaluator.ts:17204:23</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20843'>pyright-internal/src/analyzer/typeEvaluator.ts:20843:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21730'>pyright-internal/src/analyzer/typeEvaluator.ts:21730:49</a></br>at getDeclaredTypeOfSymbol <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21404'>pyright-internal/src/analyzer/typeEvaluator.ts:21404:31</a></br>at getEffectiveTypeOfSymbolForUsage <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21392'>pyright-internal/src/analyzer/typeEvaluator.ts:21392:15</a></br>at getEffectiveTypeOfSymbol <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L2831'>pyright-internal/src/analyzer/typeEvaluator.ts:2831:15</a></br>at getTypeOfModule <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L2810'>pyright-internal/src/analyzer/typeEvaluator.ts:2810:12</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at getTypingType <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/namedTuples.ts#L91'>pyright-internal/src/analyzer/namedTuples.ts:91:37</a></br>    at evaluatorInterface <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L9248'>pyright-internal/src/analyzer/typeEvaluator.ts:9248:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3751'>pyright-internal/src/analyzer/typeEvaluator.ts:3751:38</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L496'>pyright-internal/src/analyzer/typeUtils.ts:496:8</a></br>at expandedType <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3744'>pyright-internal/src/analyzer/typeEvaluator.ts:3744:29</a></br>at expandSubtype <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L3775'>pyright-internal/src/analyzer/typeEvaluator.ts:3775:12</a></br>at mapSubtypesExpandTypeVars <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L9203'>pyright-internal/src/analyzer/typeEvaluator.ts:9203:25</a></br>at validateCallArguments <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L7680'>pyright-internal/src/analyzer/typeEvaluator.ts:7680:35</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1055'>pyright-internal/src/analyzer/typeEvaluator.ts:1055:43</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L15909'>pyright-internal/src/analyzer/typeEvaluator.ts:15909:38</a></br>at evaluateTypesForAssignmentStatement <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19652'>pyright-internal/src/analyzer/typeEvaluator.ts:19652:24</a></br>at evaluateTypesForStatement <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21244'>pyright-internal/src/analyzer/typeEvaluator.ts:21244:16</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L19766'>pyright-internal/src/analyzer/typeEvaluator.ts:19766:8</a></br>at evaluateTypeForSubnode <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21243'>pyright-internal/src/analyzer/typeEvaluator.ts:21243:31</a></br>    at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21555'>pyright-internal/src/analyzer/typeEvaluator.ts:21555:35</a></br>

Another similar stack:

TypeError: Cannot read properties of undefined (reading 'category')</br>at category <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/types.ts#L2447'>pyright-internal/src/analyzer/types.ts:2447:16</a></br>    at value <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2620'>pyright-internal/src/analyzer/typeUtils.ts:2620:48</a></br>at Array.filter (<anonymous>)</br>at filter <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2619'>pyright-internal/src/analyzer/typeUtils.ts:2619:42</a></br>at filterClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeUtils.ts#L2645'>pyright-internal/src/analyzer/typeUtils.ts:2645:20</a></br>at type <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17218'>pyright-internal/src/analyzer/typeEvaluator.ts:17218:37</a></br>at classType <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16291'>pyright-internal/src/analyzer/typeEvaluator.ts:16291:74</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17206'>pyright-internal/src/analyzer/typeEvaluator.ts:17206:21</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L17204'>pyright-internal/src/analyzer/typeEvaluator.ts:17204:23</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20843'>pyright-internal/src/analyzer/typeEvaluator.ts:20843:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21166'>pyright-internal/src/analyzer/typeEvaluator.ts:21166:29</a></br>    at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21555'>pyright-internal/src/analyzer/typeEvaluator.ts:21555:35</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21497'>pyright-internal/src/analyzer/typeEvaluator.ts:21497:14</a></br>at getEffectiveTypeOfSymbolForUsage <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L4254'>pyright-internal/src/analyzer/typeEvaluator.ts:4254:42</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1040'>pyright-internal/src/analyzer/typeEvaluator.ts:1040:43</a></br>    at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16256'>pyright-internal/src/analyzer/typeEvaluator.ts:16256:30</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16240'>pyright-internal/src/analyzer/typeEvaluator.ts:16240:23</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20843'>pyright-internal/src/analyzer/typeEvaluator.ts:20843:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21730'>pyright-internal/src/analyzer/typeEvaluator.ts:21730:49</a></br>at getDeclaredTypeOfSymbol <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21404'>pyright-internal/src/analyzer/typeEvaluator.ts:21404:31</a></br>at getEffectiveTypeOfSymbolForUsage <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L4254'>pyright-internal/src/analyzer/typeEvaluator.ts:4254:42</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L1040'>pyright-internal/src/analyzer/typeEvaluator.ts:1040:43</a></br>    at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16256'>pyright-internal/src/analyzer/typeEvaluator.ts:16256:30</a></br>at Array.forEach (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L16240'>pyright-internal/src/analyzer/typeEvaluator.ts:16240:23</a></br>at getTypeOfClass <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20843'>pyright-internal/src/analyzer/typeEvaluator.ts:20843:38</a></br>at getTypeForDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21166'>pyright-internal/src/analyzer/typeEvaluator.ts:21166:29</a></br>    at getInferredTypeOfDeclaration <a href='https://github.com/microsoft/pyrx/blob/d40b99a744cbf002207adae6eba6a15920dd2491/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L21555'>pyright-internal/src/analyzer/typeEvaluator.ts:21555:35</a></br>    at Array.forEach (<anonymous>)</br>

**Comment by erictraut** [comment]
This is a crash in the `computeMroLinearization` function. It appears that something is getting corrupted in the list of base classes (or their class inheritance chains). This code hasn't changed in a _long_ time, so it's odd that we're seeing new crashes now.

My best guess is that there's some other code that's corrupting data structures, and the crash happens to occur within this code. One hypothesis is that there's some circular dependency that `getTypeOfClass` is not handling properly — for example, if a base class refers to itself somehow. That's just speculation. Without a repro case, this will be difficult to track down.

@debonte, perhaps you could do a code review of the `computeMroLinearization`? I just reviewed it, and I don't see anything wrong, but a second set of eyes would be good.

My only other thought is that we could put some assertions in place within this code that will trigger crashes with more details.

**Comment by erictraut** [comment]
I've added some additional debugging code that will hopefully help us track down the root cause of the crash. We'll need to wait two to three weeks for this debug code to make it into the production release of pylance and for additional crash logs to be collected and analyzed.

**Comment by debonte** [comment]
Sorry for the delay. Nothing in `computeMroLinearization` jumped out at me either. Thanks for adding the additional asserts.

**Comment by erictraut** [comment]
@debonte, could you check the latest pylance telemetry to see if this crash is still occurring? If not, we can close this.
