### ISSUE TITLE
pyright run takes too long and fails

### ISSUE THREAD

**Issue by ShantanuKumar** [microsoft/pyright#6225]
**Describe the bug**
We run pyright in our CI/CD on gitlab using `pre-commit` and sometimes it takes too long and then fails. See below the traceback

**Code or Screenshots**
It's hard to reproduce it though since it happens in a row few times, then stops and then happens again.

```
>> pre-commit run pyright -v --all-files --show-diff-on-failure
pyright..................................................................Failed
- hook id: pyright
- duration: 466.45s
- exit code: 1
/opt/venv/lib/python3.8/site-packages/nodeenv.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
 * Install prebuilt node (21.0.0) .Incomplete read while readingfrom https://nodejs.org/download/release/v21.0.0/node-v21.0.0-linux-x64.tar.gz - IncompleteRead(1212146 bytes read, 46646792 more expected)
Incomplete read while readingfrom https://nodejs.org/download/release/v21.0.0/node-v21.0.0-linux-x64.tar.gz - IncompleteRead(3702514 bytes read, 44156424 more expected)
Incomplete read while readingfrom https://nodejs.org/download/release/v21.0.0/node-v21.0.0-linux-x64.tar.gz - IncompleteRead(2522866 bytes read, 45336072 more expected)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 1540, in <module>
    main()
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 1122, in main
    create_environment(env_dir, args)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 998, in create_environment
    install_node(env_dir, src_dir, args)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 755, in install_node
    install_node_wrapped(env_dir, src_dir, args)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 778, in install_node_wrapped
    download_node_src(node_url, src_dir, args)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 606, in download_node_src
    dl_contents = _download_node_file(node_url)
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 598, in _download_node_file
    raise e
  File "/opt/venv/lib/python3.8/site-packages/nodeenv.py", line 590, in _download_node_file
    return io.BytesIO(urlopen(node_url).read())
  File "/usr/local/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(2522866 bytes read, 45336072 more expected)
WARNING: there is a new pyright version available (v1.1.299 -> v1.1.332).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`
Traceback (most recent call last):
  File "/opt/venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/venv/lib/python3.8/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/opt/venv/lib/python3.8/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
  File "/opt/venv/lib/python3.8/site-packages/pyright/cli.py", line 25, in run
    pkg_dir = install_pyright(args, quiet=None)
  File "/opt/venv/lib/python3.8/site-packages/pyright/_utils.py", line 61, in install_pyright
    node.run(
  File "/opt/venv/lib/python3.8/site-packages/pyright/node.py", line 98, in run
    binary = _ensure_available(target)
  File "/opt/venv/lib/python3.8/site-packages/pyright/node.py", line 37, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
  File "/opt/venv/lib/python3.8/site-packages/pyright/node.py", line 64, in _ensure_node_env
    _install_node_env()
  File "/opt/venv/lib/python3.8/site-packages/pyright/node.py", line 91, in _install_node_env
    subprocess.run(args, check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/venv/bin/python', '-m', 'nodeenv', '/home/cicd/.cache/pyright-python/nodeenv']' returned non-zero exit status 1.
```

**VS Code extension or command-line**
We run it using `pre-commit` hook and the pyright version is `v1.1.299`

**Comment by ShantanuKumar** [comment]
It might just be node issue. Although I am not too familiar with node.

**Comment by erictraut** [comment]
It looks like you're using the community-maintained ["pyright" Python package](https://github.com/RobertCraigie/pyright-python). Based on the log above, it's running into an issue installing node into your CI package. 

I've never used gitlab, so I don't know anything about its CI/CD actions. Is there a way to specify that you want to use a base container that already has node installed? That way, you wouldn't need to install it on every pyright run.

In any case, this doesn't appear to be an issue in pyright itself, so I'm going to close this issue.
