### ISSUE TITLE
Error: Debug Failure. False expression: Check called before binding

### ISSUE THREAD

**Issue by judej** [microsoft/pyright#6393]
pyright 1.1.334
Error: Debug Failure. False expression: Check called before binding
at assert pyright-internal/src/analyzer/sourceFile.ts:781:8
at callback pyright-internal/src/common/logTracker.ts:57:19
at log pyright-internal/src/analyzer/program.ts:1874:32
at callback pyright-internal/src/analyzer/typeEvaluator.ts:590:19
at callback pyright-internal/src/common/timing.ts:44:27
at runWithCancellationToken pyright-internal/src/analyzer/program.ts:1045:40
at _runEvaluatorWithCancellationToken pyright-internal/src/analyzer/program.ts:638:20
at analyze pyright-internal/src/analyzer/analysis.ts:52:32
at this pyright-internal/src/backgroundAnalysisBase.ts:484:12
at handleResumeAnalysis pyright-internal/src/backgroundAnalysisBase.ts:336:21
at None pylance-internal/src/commands/commandController.ts:83:32
at onMessage pyright-internal/src/backgroundAnalysisBase.ts:630:24
at func (node::735:20)
at func (node::23:28)

**Comment by erictraut** [comment]
Thanks for reporting. I can confirm that this is a duplicate of https://github.com/microsoft/pyright/issues/6383, which is already fixed.
