### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'computedVariance')

### ISSUE THREAD

**Issue by judej** [microsoft/pyright#6581]
been seeing this since pylance insiders 2023.11.12 which went out on november 8th which included pyright 1.1.335

```
TypeError: Cannot read properties of undefined (reading 'computedVariance')
at computedVariance /src/analyzer/types.ts:2627:30
at getVariance src/analyzer/typeEvaluator.ts:3919:45
at func (<anonymous>)
at map src/analyzer/typeEvaluator.ts:3914:56
at callback src/analyzer/typeUtils.ts:726:8
at expandedType src/analyzer/typeEvaluator.ts:3831:16
at expandSubtype src/analyzer/typeEvaluator.ts:3871:16
at func (<anonymous>)
at forEach src/analyzer/typeEvaluator.ts:3870:21
at mapSubtypesExpandTypeVars src/analyzer/typeEvaluator.ts:11725:22
at validateArgType src/analyzer/typeEvaluator.ts:11098:30
at func (<anonymous>)
at forEach src/analyzer/typeEvaluator.ts:11097:31
at validateFunctionArgumentTypes src/analyzer/typeEvaluator.ts:10820:19
at callback src/analyzer/typeEvaluator.ts:19839:27
at useSpeculativeMode src/analyzer/typeEvaluator.ts:8421:35
at validateOverloadsWithExpandedTypes src/analyzer/typeEvaluator.ts:8833:31
at validateOverloadedFunctionArguments src/analyzer/typeEvaluator.ts:9308:27
at errorNode src/analyzer/typeEvaluator.ts:9001:28
at callback src/analyzer/typeEvaluator.ts:19833:19
at useSpeculativeMode src/analyzer/typeEvaluator.ts:8997:23
at callback src/analyzer/typeUtils.ts:726:8
at expandedType src/analyzer/typeEvaluator.ts:3831:16
at expandSubtype src/analyzer/typeEvaluator.ts:3874:12
at mapSubtypesExpandTypeVars src/analyzer/typeEvaluator.ts:8993:25
at node src/analyzer/typeEvaluator.ts:1027:43
at getTypeOfExpression src/analyzer/typeEvaluator.ts:18810:20
```

**Comment by erictraut** [comment]
I found and fixed this issue already. It's addressed in pyright 1.1.338.
