### ISSUE TITLE
Crash when running language server

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#6676]
Uncaught Error Error: Debug Failure. undefined is not expected
    at onMessage (/home/rich/source/pyright/packages/pyright-internal/src/backgroundAnalysisBase.ts:222:23)
    at <anonymous> (/home/rich/source/pyright/packages/pyright-internal/src/backgroundAnalysisBase.ts:197:62)
    at emit (events:513:28)
    at <anonymous> (internal/worker:233:53)
    at [nodejs.internal.kHybridDispatch] (internal/event_target:735:20)
    at exports.emitMessage (internal/per_context/messageport:23:28)
    at callbackTrampoline (internal/async_hooks:130:17)

I didn't test with the background thread on. Pylance's perf tests caught this.

**Comment by rchiodo** [comment]
Perf tests kicked off when I submitted to main. Seems the debugger disables the background thread. Hopefully I can prevent this in the future when I write the LSP based tests (which can have a bg thread in the test).

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.340, which I just published. It will be included in a future release of pylance.
