### ISSUE TITLE
Install pyright in Docker container for NVim

### ISSUE THREAD

**Issue by mina-tech8** [microsoft/pyright#7236]
**Describe the bug**
Hello, i am getting this error for pyright as NVim LSP server:
``` 
[START][2024-02-09 10:51:14] LSP logging initiated
[ERROR][2024-02-09 10:51:14] .../vim/lsp/rpc.lua:734  "rpc" "/home/udocker/.local/share/nvim/mason/bin/pyright-langserver"  "stderr"  '/home/udocker/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/vendor.js:2\nexports.id=736,exports.ids=[736],exports.modules={2034:(A,e,t)=>{"use strict      ";const r=t(7627),o=global.Date;class i extends o{constructor(A){super(A),this.isDate=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}`}}A.exports=A=>{const e=new i(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},1374:(A,e,t)=>{"use       strict";const r=t(7627);class o extends Date{constructor(A){super(A+"Z"),this.isFloating=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}T${r(2,this.getUTCHours())}:${r(2,this.getUTCMinutes())}:${r(2,this.getUTCSeconds())}.${r(3,this.getUTCMilliseco      nds())}`}}A.exports=A=>{const e=new o(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},264:A=>{"use strict";A.exports=A=>{const e=new Date(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},6872:(A,e,t)=>{"use s\n\nSyntaxError: Unexpected token ;\n    at Module._compile (i      nternal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3      )\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.s.f.require (/home/udocker/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/pyright-langserver.js:1:1895)\n    at Promise.all.Object.keys.reduce (/home      /udocker/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/pyright-langserver.js:1:1363)\n    at Array.reduce (<anonymous>)\n' 
```

**Code or Screenshots**
My Dockerfile is this one (the same configurations of NVim (i.e., the lua files) work without problems when not in Docker):

```Dockerfile
## NVim
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ninja-build \
  gettext \
  cmake \
  unzip \
  curl \
  git \
  python3 \
  python3-dev \
  python3-pip \
  tzdata \
  npm \             # required by Mason
  python3-venv \    # required by Mason
  && rm -rf /var/lib/apt/lists/* 

ENV TZ=Europe/Berlin

WORKDIR /tmp/nvim/
RUN git clone --depth 1 --branch v0.9.4 https://github.com/neovim/neovim
RUN cd neovim && make CMAKE_BUILD_TYPE=Release
RUN cd neovim && make install

RUN useradd -ms /bin/bash udocker
RUN chown udocker /home/udocker/
USER udocker
RUN echo "alias vim=nvim" > /home/udocker/.bash_aliases

RUN pip install --upgrade pip

WORKDIR /home/udocker/.config/nvim/
ADD --chown=udocker init.lua init.lua
ADD --chown=udocker lua/*.lua lua/
ADD --chown=udocker lua/plugins/* lua/plugins/

RUN nvim --headless "+Lazy! sync" +qa
RUN nvim --headless "+MasonInstall black isort pyright ruff" +qa

WORKDIR /home/udocker
```

**VS Code extension or command-line**
I try to run pyright as an LSP for NVim, the installed pyright version is:  1.1.350

**Comment by erictraut** [comment]
The maintainers of pyright have no experience with NVim, so we're unable to help you here. The maintainers of NVim or its LSP support may be able to provide you with answers.

**Comment by mferrandon** [comment]
Hello,

the error is still present even without NVim. I think it has something to do with the Docker datetime configuration (?.

I edited the Dockefile to install pyright from npm, in one version i used ```ubuntu``` as image source, and on the other i used the ```phusion/baseimage:dev-jammy-1.1.0``` image. 
For the phusion Dockerfile, there is no error when invoking ```pyright``` from the command line, whereas for```ubuntu``` i get the same error as before, namely:

```
udocker@62981fee1b5c:~$ pyright
/usr/local/lib/node_modules/pyright/dist/vendor.js:2
exports.id=736,exports.ids=[736],exports.modules={2034:(A,e,t)=>{"use strict";const r=t(7627),o=global.Date;class i extends o{constructor(A){super(A),this.isDate=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}`}}A.exports=A=>{const e=new i(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},1374:(A,e,t)=>{"use strict";const r=t(7627);class o extends Date{constructor(A){super(A+"Z"),this.isFloating=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}T${r(2,this.getUTCHours())}:${r(2,this.getUTCMinutes())}:${r(2,this.getUTCSeconds())}.${r(3,this.getUTCMilliseconds())}`}}A.exports=A=>{const e=new o(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},264:A=>{"use strict";A.exports=A=>{const e=new Date(A);if(isNaN(e))throw new TypeError("Invalid Datetime");return e}},6872:(A,e,t)=>{"use strict";const r=t(7627);class o extends D

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.s.f.require (/usr/local/lib/node_modules/pyright/dist/pyright.js:1:1970)
    at Promise.all.Object.keys.reduce (/usr/local/lib/node_modules/pyright/dist/pyright.js:1:1438)
    at Array.reduce (<anonymous>)
```

These are the Dockerfiles, can switch from source images on first/second line.
```Dockerfile
FROM ubuntu:20.04
# FROM phusion/baseimage:dev-jammy-1.1.0

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ninja-build \
  gettext \
  cmake \
  unzip \
  curl \
  git \
  python3 \
  python3-dev \
  python3-pip \
  tzdata \
  npm \
  python3-venv \
  && rm -rf /var/lib/apt/lists/* 

ENV TZ=Europe/Berlin

RUN npm install -g pyright

RUN useradd -ms /bin/bash udocker
RUN chown udocker /home/udocker/
USER udocker

WORKDIR /home/udocker
```
