### ISSUE TITLE
Pyright returns exit code 1 in neovim while getting DateTime

### ISSUE THREAD

**Issue by agctute** [microsoft/pyright#7349]
I'm currently inside an Ubuntu 20.04 VM, where I installed the pyright lsp (VERSION 1.1.351) using Mason inside of Neovim. When pyright initializes, it returns the following error in lsp.log:
```
[ERROR][2024-02-26 14:14:12] .../vim/lsp/rpc.lua:31	"rpc"	"/home/john/.local/share/nvim/mason/bin/pyright-langserver"	"stderr"	
'/home/john/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/vendor.js:2\nexports.id=968,exports.ids=[968],
exports.modules={6596:(A,e,t)=>{"use strict";const r=t(1160),o=global.Date;
class i extends o{constructor(A){super(A),this.isDate=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-${r(2,this.getUTCDate())}`}}
A.exports=A=>{const e=new i(A);
if(isNaN(e))throw new TypeError("Invalid Datetime");
return e}},4023:(A,e,t)=>{"use strict";
const r=t(1160);
class o extends Date{constructor(A){super(A+"Z"),this.isFloating=!0}toISOString(){return`${this.getUTCFullYear()}-${r(2,this.getUTCMonth()+1)}-
${r(2,this.getUTCDate())}T${r(2,this.getUTCHours())}:${r(2,this.getUTCMinutes())}:${r(2,this.getUTCSeconds())}.${r(3,this.getUTCMilliseconds())}`}}A.exports=A=>{const e=new o(A);
if(isNaN(e))throw new TypeError("Invalid Datetime");
return e}},692:A=>{"use strict";
A.exports=A=>{const e=new Date(A);
if(isNaN(e))throw new TypeError("Invalid Datetime");
return e}},7640:(A,e,t)=>{"use s\n\nSyntaxError: Unexpected token ;\n  
at Module._compile (internal/modules/cjs/loader.js:723:23)\n    
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n 
at Module.load (internal/modules/cjs/loader.js:653:32)\n    
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    
at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    
at Module.require (internal/modules/cjs/loader.js:692:17)\n    
at require (internal/modules/cjs/helpers.js:25:18)\n    
at Object.s.f.require (/home/john/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/pyright-langserver.js:1:1891)\n    
at Promise.all.Object.keys.reduce (/home/john/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/pyright-langserver.js:1:1360)\n    
at Array.reduce (<anonymous>)\n'  
```
This was all returned to me in a single line and the line breaks are added for better reading.

**Comment by erictraut** [comment]
I don't have any experience with mason or neovim. I know that pyright is working fine as a language server for other editors, so this is likely a problem on the mason or neovim side. Your best bet is to work with those maintainers.

One thing you might want to do is to verify that you have an up-to-date version of node installed on your system. The error looks like something that an older version of node might cause.

**Comment by agctute** [comment]
Thanks for the pointer. I did notice that it said node was outdated. Guess ignoring warnings is finally coming to bite me.
