### ISSUE TITLE
Debug failure for invalid type alias statement 

### ISSUE THREAD

**Issue by dhruvmanila** [microsoft/pyright#7933]
**Describe the bug**

It seems like the server is failing to possibly log the syntax error for the following code:
```py
type def = 1
```

Here, `def` is a keyword but is not allowed in that position, only soft keywords are allowed there.

**Code or Screenshots**

The code is mentioned above. The error traceback is:

```
2024-05-16 07:51:24 [ERROR] An internal error occurred while parsing file "/Users/dhruv/playground/ruff/parser/_.py": Error: Debug Failure. False expression.
    at C._parseTypeAliasStatement (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:481:9)
    at C._parseSmallStatement (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:2982:33)
    at C._parseSimpleStatement (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:2891:41)
    at C._parseStatement (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:449:21)
    at callback (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:267:44)
    at a.timeOperation (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:44:28)
    at C.parseSourceFile (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/parser/parser.ts:252:35)
    at t.SourceFile._parseFile (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/analyzer/sourceFile.ts:1414:23)
    at callback (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/analyzer/sourceFile.ts:647:47)
    at t.LogTracker.log (/opt/homebrew/lib/node_modules/pyright/dist/pyright-internal/src/common/logTracker.ts:61:20)
```

**VS Code extension or command-line**

I've tried it using both and I'm getting the same error on both:
* Pyright version (via the CLI): `pyright 1.1.363`
* Pylance version (via VS Code): `v2024.5.1`

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.364.
