### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fileInfo')

### ISSUE THREAD

**Issue by judej** [microsoft/pyright#8666]
Seeing several of these on the insiders release:: 2024.7.103 pyrightVersion: 1.1.373

```
TypeError: Cannot read properties of undefined (reading 'fileInfo')
at fileInfo /src/analyzer/analyzerNodeInfo.ts#L177'>pyright-internal/src/analyzer/analyzerNodeInfo.ts:177:17
at getFileInfo /src/analyzer/program.ts#L2035'>pyright-internal/src/analyzer/program.ts:2035:46
at callback /src/common/logTracker.ts#L61'>pyright-internal/src/common/logTracker.ts:61:19
at log /src/analyzer/program.ts#L1895'>pyright-internal/src/analyzer/program.ts:1895:32
at callback /src/analyzer/typeEvaluator.ts#L636'>pyright-internal/src/analyzer/typeEvaluator.ts:636:19
at callback /src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19
at runWithCancellationToken /src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:40
at _runEvaluatorWithCancellationToken /src/analyzer/program.ts#L620'>pyright-internal/src/analyzer/program.ts:620:20
at analyze /src/analyzer/analysis.ts#L57'>pyright-internal/src/analyzer/analysis.ts:57:32
at this /src/backgroundAnalysisBase.ts#L508'>pyright-internal/src/backgroundAnalysisBase.ts:508:12
at handleResumeAnalysis /src/backgroundAnalysisBase.ts#L501'>pyright-internal/src/backgroundAnalysisBase.ts:501:13
at None src/backgroundAnalysis.ts#L416'>pylance-internal/src/backgroundAnalysis.ts:416:28
at handleAnalyze /src/backgroundAnalysisBase.ts#L351'>pyright-internal/src/backgroundAnalysisBase.ts:351:21
at None src/backgroundAnalysis.ts#L404'>pylance-internal/src/backgroundAnalysis.ts:404:28
at onMessage /src/backgroundAnalysisBase.ts#L670'>pyright-internal/src/backgroundAnalysisBase.ts:670:24
    at func (node:<REDACTED: user-file-path>:825:20)
    at func (node:<REDACTED: user-file-path>:23:28)
```

**Comment by erictraut** [comment]
@judej, this is in Pylance-specific code and it specifically applies to notebooks. I think Heejae added it. Please transfer this to the pylance-release project and triage/prioritize as you see fit.
