### ISSUE TITLE
Errors when launching VSCode with pyright enabled

### ISSUE THREAD

**Issue by joeparis** [microsoft/pyright#883]
**Describe the bug**
When pyright is enabled, launching VS Code results in the following errors on launch:

![2020-07-23_21-02-38 (Custom) (1)](https://user-images.githubusercontent.com/2662123/88360358-37fefe00-cd2a-11ea-8930-d5b5c8d0526b.png)

**To Reproduce**
Install and enable pylance.

**Expected behavior**
I expect *not* to get the error messages. 😉 

**VS Code extension or command-line**
I am running version 1.1.55 of the VS Code extension.

**Additional context**
I have recently installed pylance and pyright and am getting the errors shown above when I launch VS Code. If I disable pyright the errors do not occur, even with pylance still enabled. I've included (what I hope are) the relevant logs from the output window below.

***pyright log***

```
[Info  - 8:55:50 PM] Pyright language server 1.1.55 starting
[Info  - 8:55:50 PM] Server root directory: c:\Users\joepa\.vscode\extensions\ms-pyright.pyright-1.1.55
Received pythonPath from Python extension: C:\Users\joepa\AppData\Local\Programs\Python\Python38\python.exe
[Info  - 8:55:51 PM] Background analysis root directory: c:\Users\joepa\.vscode\extensions\ms-pyright.pyright-1.1.55
[Info  - 8:55:51 PM] Background analysis started
```

***python log***

```
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> pyenv root
> python3.7 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-07-23 20:55:52: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-07-23 20:55:53: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.8-64
 -3.7-64
 -2.7-64 does not exist
Error 2020-07-23 20:55:53: Failed to get interpreter information for 'C:\Users\joepa\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\joepa\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py" "c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\joepa\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\joepa\\.vscode\\extensions\\ms-python.python-2020.7.96456\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\joepa\\.vscode\\extensions\\ms-python.python-2020.7.96456\\pythonFiles\\interpreterInfo.py"'
}
Starting Pylance language server.
Python interpreter path: ~\AppData\Local\Programs\Python\Python38\python.exe
Error 2020-07-23 20:55:53: Failed to get interpreter information for 'C:\Users\joepa\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\joepa\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py" "c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\joepa\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\joepa\\.vscode\\extensions\\ms-python.python-2020.7.96456\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\joepa\\.vscode\\extensions\\ms-python.python-2020.7.96456\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-07-23 20:55:53: Attempted to download with skipDownload true.
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pylint --ignore-patterns '(?!test_).*\.py' --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pylint --ignore-patterns '(?!test_).*\.py' --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pycodestyle --max-doc-length 80 --max-line-length 100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pycodestyle --max-doc-length 80 --max-line-length 100 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pydocstyle c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py pydocstyle c:\Users\joepa\Dev\temp3\standardplt.py
cwd: c:\Users\joepa\Dev\temp3
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
##########Linting Output - pycodestyle##########
##########Linting Output - pydocstyle##########
c:\Users\joepa\Dev\temp3\standardplt.py:1 at module level:
        D100: Missing docstring in public module
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

***python language server log***

```
[Info  - 8:55:54 PM] Pylance language server 2020.7.3 (pyright 5004efe5) starting
[Info  - 8:55:54 PM] Server root directory: c:\Users\joepa\.vscode\extensions\ms-python.vscode-pylance-2020.7.3\server
[Error - 8:55:54 PM] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
    at _.registerCommand (c:\Users\joepa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:629:946)
    at Object.registerCommand (c:\Users\joepa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:911:119)
    at J.register (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:270996)
    at J.initialize (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:270554)
    at v.initializeFeatures (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:289508)
    at c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:281528
[Error - 8:55:54 PM] Starting client failed
Error: command 'pyright.createtypestub' already exists
    at _.registerCommand (c:\Users\joepa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:629:946)
    at Object.registerCommand (c:\Users\joepa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:911:119)
    at J.register (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:270996)
    at J.initialize (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:270554)
    at v.initializeFeatures (c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:289508)
    at c:\Users\joepa\.vscode\extensions\ms-python.python-2020.7.96456\out\client\extension.js:1:281528
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640

```

**Comment by joeparis** [comment]
From the documentation:

> Note: If you are a Pyright extension user in VS Code, you’ll want to uninstall Pyright when installing Pylance. All Pyright functionality is included in Pylance. By having both extensions installed, you may encounter installation conflicts and see duplicative diagnostics (e.g., errors, warnings) surface in your code.

I am an idiot.
