### ISSUE TITLE
No matching version found for pyright@1.1.379

### ISSUE THREAD

**Issue by cheginit** [microsoft/pyright#8949]
I am using Pixi to manage my package and when I updated `pyright` to v1.1.379 it fails to install it. The issue appears to be with `npm` not being able to find this version since it works with previous versions, e.g., v1.1.378. Here's the installation log:

```
0 verbose cli /opt/homebrew/Cellar/node/22.8.0/bin/node /opt/homebrew/bin/npm
1 info using npm@10.8.2
2 info using node@v22.8.0
3 silly config load:file:/opt/homebrew/lib/node_modules/npm/npmrc
4 silly config load:file:~/.cache/pyright-python/1.1.379/.npmrc
5 silly config load:file:~/.npmrc
6 silly config load:file:~/.npm-global/etc/npmrc
7 verbose title npm install pyright@1.1.379
8 verbose argv "install" "pyright@1.1.379"
9 verbose logfile logs-max:10 dir:~/.npm/_logs/2024-09-10T15_46_19_051Z-
10 verbose logfile ~/.npm/_logs/2024-09-10T15_46_19_051Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest pyright@1.1.379
16 silly packumentCache full:https://registry.npmjs.org/pyright cache-miss
17 http fetch GET https://registry.npmjs.org/pyright attempt 1 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
18 http fetch GET https://registry.npmjs.org/pyright attempt 2 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
19 http fetch GET https://registry.npmjs.org/pyright attempt 3 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
20 http fetch GET 200 https://registry.npmjs.org/pyright 70190ms (cache stale)
21 silly packumentCache full:https://registry.npmjs.org/pyright set size:1302690 disposed:false
22 silly placeDep ROOT pyright@ OK for: pyright-binaries@1.0.0 want: 1.1.379
23 verbose type version
24 verbose stack pyright: No matching version found for pyright@1.1.379.
24 verbose stack     at module.exports (/opt/homebrew/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
24 verbose stack     at RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
24 verbose stack     at async #fetchManifest (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1199:20)
24 verbose stack     at async #nodeFromEdge (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1037:19)
24 verbose stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
24 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
24 verbose stack     at async Promise.all (index 1)
24 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
24 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:150:5)
24 verbose stack     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
25 error code ETARGET
26 error notarget No matching version found for pyright@1.1.379.
27 error notarget In most cases you or one of your dependencies are requesting
27 error notarget a package version that doesn't exist.
28 silly unfinished npm timer reify 1725983179152
29 silly unfinished npm timer reify:loadTrees 1725983179153
30 verbose cwd ~/.cache/pyright-python/1.1.379
31 verbose os Darwin 23.6.0
32 verbose node v22.8.0
33 verbose npm  v10.8.2
34 verbose exit 1
35 verbose code 1
36 error A complete log of this run can be found in: ~/.npm/_logs/2024-09-10T15_46_19_051Z-debug-0.log
```

Note that I removed `~/.cache/pyright-python/` just to be sure there's no issue with installing previous versions, and was able to successfully install v1.1.378.

**Comment by erictraut** [comment]
I'm not familiar with Pixi. Are you able to install pyright 1.1.379 using npm directly? Perhaps you encountered a temporary outage from the npm registry? I confirmed that 1.1.379 was [published successfully](https://www.npmjs.com/package/pyright).

From the log above, there are several mentions of "UNABLE_TO_GET_ISSUER_CERT_LOCALLY", which could indicate that there's some cert misconfiguration on your side. Perhaps an expired cert?

In any case, I don't think this is a general pyright bug, so I'm going to close the issue. If you find additional clues that indicate otherwise, I'm happy to reopen and investigate further.
