### ISSUE TITLE
nodeenv subprocess command returned non-zero exit status 1 (OSError: Cannot assign requested address)

### ISSUE THREAD

**Issue by lexicalunit** [microsoft/pyright#9021]
**Describe the bug**
`pyright` in our CI/CD pipelines began to fail earlier today with this stack trace:

```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/circleci/project/venv/lib/python3.12/site-packages/nodeenv.py", line 1519, in <module>
    main()
  File "/home/circleci/project/venv/lib/python3.12/site-packages/nodeenv.py", line 1093, in main
    args.node = get_last_stable_node_version()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/nodeenv.py", line 1026, in get_last_stable_node_version
    return _get_versions_json()[0]['version'].lstrip('v')
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/nodeenv.py", line 1002, in _get_versions_json
    response = urlopen('%s/index.json' % src_base_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/nodeenv.py", line 624, in urlopen
    return urllib2.urlopen(req)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
Traceback (most recent call last):
  File "/home/circleci/project/venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/cli.py", line 25, in run
    pkg_dir = install_pyright(args, quiet=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/_utils.py", line 64, in install_pyright
    node.run(
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/node.py", line 105, in run
    binary = _ensure_available(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/node.py", line 38, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/node.py", line 65, in _ensure_node_env
    _install_node_env()
  File "/home/circleci/project/venv/lib/python3.12/site-packages/pyright/node.py", line 98, in _install_node_env
    subprocess.run(args, check=True)
  File "/home/circleci/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/circleci/project/venv/bin/python3', '-m', 'nodeenv', '/home/circleci/.cache/pyright-python/nodeenv']' returned non-zero exit status 1.
```

**Code or Screenshots**
Our code has not changed.

**VS Code extension or command-line**
Command line. In the CI/CD pipeline we are running the following command:
```sh
pyright .
```

I attempted to fix things by updating to version 1.1.380 -- but that did not seem to help and we still get the same error.

**Comment by erictraut** [comment]
This error message isn't coming from pyright. It appears to be coming from the community-maintained [Python wrapper for pyright](https://github.com/RobertCraigie/pyright-python). If you file an issue in that project, its maintainer should be able to help you diagnose the issue. Sorry I can't be of more help here.

**Comment by lexicalunit** [comment]
@erictraut Is there a way to invoke `pyright` on the CLI w/o using the wrapper? That is my intention. I figured that we could install `pyright` by ising `pip install pyright`... but I guess that just installs the wrapper 🤔
