### ISSUE TITLE
pyright won't start with node v20.18.0: Invalid regular expression SyntaxError

### ISSUE THREAD

**Issue by hholst80** [microsoft/pyright#9383]
**Describe the bug**

pyright does not run.

```
# python3 --version
Python 3.12.2
# node --version
v20.18.0 
```

**Code or Screenshots**

```
# source venv/bin/activate.fish
(venv) root@xps ... (master)
# pip freeze
nodeenv==1.9.1
pyright==1.1.387
typing_extensions==4.12.2
(venv) root@xps ... (master)
# pyright

[snip]

SyntaxError: Invalid regular expression: /\(\?P?<([\p{ID_Start}$_][\p{ID_Continue}$_\u200C\u200D]*)>/u: Invalid property name in character class
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at o.f.require (/root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:2316)
    at /root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:1784
    at Array.reduce (<anonymous>)

Node.js v20.18.0
(venv) root@xps ... (master) [0|1]
# 
```

**Comment by hholst80** [comment]
@erictraut thanks! For anyone else finding this issue, I reported it here:

https://github.com/RobertCraigie/pyright-python/issues/320
