### ISSUE TITLE
pyright 404 on npm

### ISSUE THREAD

**Issue by JacobHayes** [microsoft/pyright#9563]
**Describe the bug**

The npm upload of pyright is missing (or private or something?) - https://www.npmjs.com/package/pyright is giving a 404 (but is still cached in searches) and installing pyright (eg: in CI) fails:

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/pyright - Not found
npm error 404
npm error 404  'pyright@1.1.390' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-12-08T18_35_46_777Z-debug-0.log
Traceback (most recent call last):
  File "/home/runner/work/backend/backend/.venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/runner/work/backend/backend/.venv/lib/python3.12/site-packages/pyright/cli.py", line 31, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/backend/backend/.venv/lib/python3.12/site-packages/pyright/cli.py", line 18, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/backend/backend/.venv/lib/python3.12/site-packages/pyright/cli.py", line 22, in run
    pkg_dir = install_pyright(args, quiet=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/backend/backend/.venv/lib/python3.12/site-packages/pyright/_utils.py", line 63, in install_pyright
    node.run(
  File "/home/runner/work/backend/backend/.venv/lib/python3.12/site-packages/pyright/node.py", line 144, in run
    subprocess.run(node_args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/setup-rye-2024-03-04/0.42.0/x86_64/py/cpython@3.12.3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/npm', 'install', 'pyright@1.1.390']' returned non-zero exit status 1.
```

**Comment by erictraut** [comment]
I wonder if this was a temporary glitch with the npm registry service. It seems to be working fine for me now. Can you try again?

**Comment by JacobHayes** [comment]
Yup, seems to be working now.
